Added More Categories and Players
kaboussi/stream-cli pull request #43
Opened 2022-08-19 07:37 UTC by ashroyxi

New categories (Only for TorrentGalaxy/TGX): 
- Anime
- Music
- AudioBook
- Porn

New players:
- mplayer
- smplayer

2022-08-21 16:28 UTC, ashroyxi commented
@kaboussi 
say something i guess?

2022-08-21 22:42 UTC, kaboussi commented
> @kaboussi say something i guess?

Sorry for the late reply.
it seems like you did a huge PR
i'm gonna look at it right now

2022-08-22 00:02 UTC, kaboussi requested changes
This looks so good just some little details.
thanks for this beautiful PR, and sorry again for my late response

2022-08-22 00:02 UTC, kaboussi commented on stream_cli/api/torrentgalaxy.py
> +
here too

2022-08-22 12:55 UTC, ashroyxi commented on install.sh
> +python3 -m venv venv && source venv/bin/activate
but you said support for windows is turned off #42 and i have no idea how windows works.

2022-08-22 12:57 UTC, ashroyxi commented on install.sh
> +sudo cp stream-cli /usr/bin/
editing registry from cmd is not a good idea i guess

2022-08-22 13:08 UTC, closed without merging